### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by studiobutter** [studiobuttermedia/Sky_Server_Time#2]
- [x] Separate release for Server Regions
- [ ] Add MySQL Database
- [ ] Add Eye of Eden Weekly Reset
- [ ] Auto Correct time when DST Start #4 
- [ ] In-Game Event Alert (Geyser, Grandma, Turtle, etc)
